version: '3.8'

services:
  web:
    container_name: subs_app_dev_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: subs_app_dev_web:latest
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    # environment:
    #   - DRF_ENV_FILE_NAME=.env.docker
    ports:
      - "8000:8000"
    env_file:
      - .env.docker.dev
    depends_on:
      - db
  db:
    container_name: subs_app_dev_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker.dev
    ports:
      - "5432:5432" 

volumes:
  postgres_data:
    name: subs_app_dev_postgres_data
