version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # environment:
    #   - DRF_ENV_FILE_NAME=.env.docker
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    ports:
      - "5432:5432" 


volumes:
  postgres_data:
