version: '3.8'

services:
  web:
    container_name: subs_app_prod_web
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: subs_app_prod_web:latest
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      # - media_volume:/app/mediafiles
    env_file:
      - .env.docker.prod
    depends_on:
      - db
    expose:  # Change from ports to expose
      - 8000
  db:
    container_name: subs_app_prod_db
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker.prod
    ports:
      - "5432:5432" 
  nginx:
    container_name: subs_app_prod_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx.prod
    image: subs_app_prod_nginx:latest
    volumes:
      - static_volume:/app/staticfiles
      # - media_volume:/app/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web



volumes:
  postgres_data:
    name: subs_app_prod_postgres_data
  static_volume:
    name: subs_app_prod_static_files
  # media_volume:
