# Generated by Django 5.0 on 2024-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
