# Generated by Django 5.0 on 2024-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20)),
                ('test_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'test_model',
            },
        ),
    ]
